<?xml version="1.0" encoding="utf-8"?>
<Database Name="Anbar" Class="AnbarDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Anbar;Integrated Security=True" SettingsObjectName="Application_Anbar.Properties.Settings" SettingsPropertyName="AnbarConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Phonecompany" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" OtherKey="CustomerID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.ViewRequestProduct" Member="ViewRequestProducts">
    <Type Name="ViewRequestProduct">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NeedDate" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="teadad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sellers" Member="Sellers">
    <Type Name="Seller">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellerName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Phonecompany" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Seller_EnterDoc" Member="EnterDocs" OtherKey="SellerID" Type="EnterDoc" />
    </Type>
  </Table>
  <Table Name="dbo.EnterDetails" Member="EnterDetails">
    <Type Name="EnterDetail">
      <Column Name="EnterID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyPrice" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Teadad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="EnterDoc_EnterDetail" Member="EnterDoc" ThisKey="EnterID" Type="EnterDoc" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_EnterDetail" Member="Product" ThisKey="ProductID" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EnterDocuments" Member="EnterDocs">
    <Type Name="EnterDoc">
      <Column Name="EnterID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Validate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="EnterDoc_EnterDetail" Member="EnterDetails" OtherKey="EnterID" Type="EnterDetail" />
      <Association Name="EnterDoc_SellerAccount" Member="SellerAccounts" OtherKey="EnterID" Type="SellerAccount" />
      <Association Name="Seller_EnterDoc" Member="Seller" ThisKey="SellerID" Type="Seller" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BuyPrice" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SellPrice" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mojodi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="St_mojodi" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Discountable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Product_EnterDetail" Member="EnterDetails" OtherKey="ProductID" Type="EnterDetail" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" OtherKey="ProductID" Type="OrderDetail" />
      <Association Name="Product_Request" Member="Requests" OtherKey="ProductID" Type="Request" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" Type="Category" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Validate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" OtherKey="OrderID" Type="OrderDetail" />
      <Association Name="Order_CustomerAccount" Member="CustomerAccounts" OtherKey="OrderID" Type="CustomerAccount" />
      <Association Name="Order_Cheque" Member="Cheques" OtherKey="OrderID" Type="Cheque" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellPrice" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="teadad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderID" Type="Order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductID" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerAccount" Member="CustomerAccounts">
    <Type Name="CustomerAccount">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Debit" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Creditor" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Order_CustomerAccount" Member="Order" ThisKey="OrderID" Type="Order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SellerAccount" Member="SellerAccounts">
    <Type Name="SellerAccount">
      <Column Name="EnterID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Creditor" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Debit" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="EnterDoc_SellerAccount" Member="EnterDoc" ThisKey="EnterID" Type="EnterDoc" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cheque" Member="Cheques">
    <Type Name="Cheque">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChequeNumber" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChequeQuantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AcountNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="OwnerAcounnt" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="DateCheque" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Order_Cheque" Member="Order" ThisKey="OrderID" Type="Order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassUser" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="SaveImport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SaveExport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RemoveImort" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RemoveExport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockAccountDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountCustomer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountSeller" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReachDocument" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowReport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ManageUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Requests" Member="Requests">
    <Type Name="Request">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NeedDate" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="teadad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_Request" Member="Product" ThisKey="ProductID" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>